### ISSUE TITLE
Join nested fields using dot

### ISSUE THREAD

**Issue by benregn** [marcdel/open_telemetry_decorator#93]
Spurred on by your quick action a couple a days ago, I have another idea for improvement. 

I'd like the nested accessed fields to be joined using a dot instead of an underscore. This would align with the default OTel way of name spacing things, e.g. `service.name` or `http.route`. I think it's also nice to have a different character to separate the nesting from naming, e.g. `my_struct.other_struct.field` vs `my_struct_other_struct_field`, making it clearer where one name ends and the next starts.

Of course this could be configurable not to break things for existing users.

**Comment by marcdel** [comment]
I gotta fix my notifications here, because I keep missing things, but yes! I was adding this to a new project yesterday and had the same idea. Lemme think about how to make it configurable because I feel like it makes sense as the default behavior, but you're right about not breaking existing users' queries.
